services:
  - type: web
    name: stock-forecaster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POLYGON_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
    autoDeploy: true
    healthCheckPath: /health